apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-operator.fullname" . }}
  labels:
    {{- include "k8s-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - kavrynt.io
    resources:
      - mcpservers
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - kavrynt.io
    resources:
      - mcpservers/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - kavrynt.io
    resources:
      - mcpservers/finalizers
    verbs:
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-operator.fullname" . }}
  labels:
    {{- include "k8s-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
