version: 2

project_name: kavryctl

builds:
  - id: kavryctl
    main: ./cmd/kavryctl
    binary: kavryctl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/kavrynt/kavryctl/internal/cli.Version={{ .Version }}
      - -X github.com/kavrynt/kavryctl/internal/cli.Commit={{ .Commit }}
      - -X github.com/kavrynt/kavryctl/internal/cli.BuildDate={{ .Date }}

archives:
  - id: kavryctl
    ids:
      - kavryctl
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - cmd/kavryctl/README.md
      - cmd/kavryctl/examples/*

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: kavrynt
    name: kavrynt
  draft: false
  prerelease: auto
