gateway:
  fullnameOverride: kavrynt-gateway
  image:
    repository: kavrynt/gateway
    tag: 0.0.2-beta.1
    pullPolicy: IfNotPresent

operator:
  fullnameOverride: kavrynt-operator
  image:
    repository: kavrynt/operator
    tag: 0.0.2-beta.1
    pullPolicy: IfNotPresent
